// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models.Configurations
{
    public partial class QuarterlyOrderConfiguration : IEntityTypeConfiguration<QuarterlyOrder>
    {
        public void Configure(EntityTypeBuilder<QuarterlyOrder> entity)
        {
            entity.ToView("Quarterly Orders");

            entity.Property(e => e.CustomerId).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<QuarterlyOrder> entity);
    }
}
